import { renderToBuffer } from '@react-pdf/renderer'
import { createHash } from 'node:crypto'
import { createElement } from 'react'
import { ContractDocument } from '@/lib/ContractDocument'
import { normalizeContractCurrency, normalizeContractLanguage, safeContractText, type ContractContent } from '@/lib/contracts'

export type ContractPdfLogContext = {
  requestId?: string
  contractId?: string
  contractNumber?: string
  versionId?: string
  startedAt?: number
}

const PDF_SIGNATURE = '%PDF-'

function assertPdfBuffer(pdf: Uint8Array) {
  const signature = Buffer.from(pdf.slice(0, 5)).toString('ascii')
  if (pdf.byteLength < 5 || signature !== PDF_SIGNATURE) {
    throw new Error(`Contract PDF renderer returned invalid output. byteLength=${pdf.byteLength} signature=${signature}`)
  }
}

function logPdfEvent(level: 'info' | 'warn' | 'error', event: string, context: ContractPdfLogContext, meta: Record<string, unknown> = {}) {
  const payload = {
    scope: 'contract-pdf-renderer',
    renderer: '@react-pdf/renderer',
    event,
    requestId: context.requestId,
    contractId: context.contractId,
    versionId: context.versionId,
    contractNumber: context.contractNumber,
    durationMs: context.startedAt ? Date.now() - context.startedAt : undefined,
    ...meta,
  }

  if (level === 'error') console.error('[contract-pdf-renderer]', payload)
  else if (level === 'warn') console.warn('[contract-pdf-renderer]', payload)
  else console.info('[contract-pdf-renderer]', payload)
}

function relationObject(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : {}
}

function normalizeStringArray(value: unknown) {
  return Array.isArray(value) ? value.map((item) => String(item ?? '').trim()).filter(Boolean) : []
}

export function normalizeContractContent(raw: unknown): ContractContent {
  const input = relationObject(raw)
  const company = relationObject(input.company)
  const client = relationObject(input.client)
  const financials = relationObject(input.financials)
  const language = normalizeContractLanguage(input.language)
  const currency = normalizeContractCurrency(input.currency ?? financials.currency)
  const sections = Array.isArray(input.sections)
    ? input.sections.map((section, index) => {
        const row = relationObject(section)
        return {
          id: safeContractText(row.id, `section-${index + 1}`),
          number: safeContractText(row.number, String(index + 1)),
          title: safeContractText(row.title, 'Contract section'),
          body: normalizeStringArray(row.body),
          riskLevel: safeContractText(row.riskLevel) || undefined,
          category: safeContractText(row.category) || undefined,
          bilingualTitle: safeContractText(row.bilingualTitle) || undefined,
          bilingualBody: normalizeStringArray(row.bilingualBody),
        }
      })
    : []

  const normalizedSections = sections.length
    ? sections
    : [
        {
          id: 'fallback',
          number: '1',
          title: 'Agreement',
          body: ['The parties agree to the professional services, commercial terms, and signature requirements recorded in TASKIT.'],
        },
      ]

  return {
    title: safeContractText(input.title, 'Professional Service Agreement'),
    subtitle: safeContractText(input.subtitle, 'Enterprise client contract generated by TASKIT.'),
    contractNumber: safeContractText(input.contractNumber, 'CONTRACT'),
    language,
    type: safeContractText(input.type, 'SERVICE_AGREEMENT'),
    status: safeContractText(input.status, 'draft'),
    currency,
    jurisdiction: safeContractText(input.jurisdiction) || null,
    governingLaw: safeContractText(input.governingLaw) || null,
    effectiveDate: safeContractText(input.effectiveDate) || null,
    expiryDate: safeContractText(input.expiryDate) || null,
    renewalTerms: safeContractText(input.renewalTerms) || null,
    paymentTerms: safeContractText(input.paymentTerms) || null,
    paymentFrequency: safeContractText(input.paymentFrequency) || null,
    serviceScope: safeContractText(input.serviceScope) || null,
    legalDisclaimer: safeContractText(
      input.legalDisclaimer,
      'This document is generated from business data and approved clauses. It should be reviewed by authorized legal counsel before external signature.'
    ),
    watermark: safeContractText(input.watermark) || null,
    company: {
      name: safeContractText(company.name, 'TASKIT'),
      contactName: safeContractText(company.contactName) || null,
      email: safeContractText(company.email) || null,
      address: safeContractText(company.address) || null,
      country: safeContractText(company.country) || null,
      taxId: safeContractText(company.taxId) || null,
    },
    client: {
      name: safeContractText(client.name, 'Client'),
      contactName: safeContractText(client.contactName) || null,
      email: safeContractText(client.email) || null,
      address: safeContractText(client.address) || null,
      country: safeContractText(client.country) || null,
      taxId: safeContractText(client.taxId) || null,
    },
    project: input.project && typeof input.project === 'object' ? (input.project as ContractContent['project']) : null,
    financials: {
      currency,
      estimatedValue: typeof financials.estimatedValue === 'number' ? financials.estimatedValue : Number(financials.estimatedValue ?? 0) || null,
      openInvoiceTotal: typeof financials.openInvoiceTotal === 'number' ? financials.openInvoiceTotal : Number(financials.openInvoiceTotal ?? 0) || null,
      openInvoiceCount: Number(financials.openInvoiceCount ?? 0) || 0,
    },
    tableOfContents: normalizedSections.map((section) => ({ number: section.number, title: section.title })),
    sections: normalizedSections,
    signatureBlocks: Array.isArray(input.signatureBlocks)
      ? input.signatureBlocks.map((item) => {
          const row = relationObject(item)
          return {
            role: safeContractText(row.role, 'Signature'),
            partyName: safeContractText(row.partyName, 'Party'),
            signerName: safeContractText(row.signerName) || null,
            signerEmail: safeContractText(row.signerEmail) || null,
          }
        })
      : [],
    aiSummary: safeContractText(input.aiSummary, 'TASKIT prepared a professionally structured agreement from workspace data.'),
    missingFields: normalizeStringArray(input.missingFields),
    generatedAt: safeContractText(input.generatedAt, new Date().toISOString()),
  }
}

export function contractPdfChecksum(pdf: Uint8Array) {
  return createHash('sha256').update(pdf).digest('hex')
}

export async function generateContractPdf(rawContract: ContractContent, context: ContractPdfLogContext = {}) {
  const contract = normalizeContractContent(rawContract)
  const logContext = {
    ...context,
    contractNumber: context.contractNumber ?? contract.contractNumber,
    startedAt: context.startedAt ?? Date.now(),
  }

  try {
    logPdfEvent('info', 'pdf-render-started', logContext, {
      language: contract.language,
      sectionCount: contract.sections.length,
    })
    const document = createElement(ContractDocument, { contract }) as unknown as Parameters<typeof renderToBuffer>[0]
    const pdf = await renderToBuffer(document)
    assertPdfBuffer(pdf)
    logPdfEvent('info', 'pdf-render-completed', logContext, { byteLength: pdf.byteLength })
    return pdf
  } catch (error) {
    logPdfEvent('error', 'pdf-render-failed', logContext, {
      error: error instanceof Error ? { name: error.name, message: error.message, stack: error.stack } : { message: String(error) },
    })
    throw error
  }
}
