export const REALTIME_EVENTS = [
  'task.created',
  'task.updated',
  'task.deleted',
  'task.submission.created',
  'comment.created',
  'comment.updated',
  'project.created',
  'project.updated',
  'project.deleted',
  'project.media.created',
  'room.created',
  'project.category.created',
  'client.created',
  'client.updated',
  'client.deleted',
  'invoice.created',
  'invoice.updated',
  'invoice.deleted',
  'invoice.paid',
  'employee.invited',
  'notification.created',
  'notification.read',
  'presence.user.online',
  'presence.user.offline',
  'presence.snapshot',
  'workspace.event',
  'social.account.connected',
  'social.account.disconnected',
  'social.sync.completed',
  'social.metrics.updated',
  'social.insight.created',
  'social.webhook.processed',
  'ai.run.completed',
  'team.member.assigned',
  'asset.updated',
  'incident.created',
  'incident.updated',
  'approval.completed',
  'finance.invoice.paid',
  'finance.account.created',
  'finance.journal_entry.created',
  'finance.journal_entry.posted',
  'finance.journal_entry.reversed',
  'task_created',
  'task_updated',
  'task_deleted',
  'task_submission_created',
  'comment_created',
  'comment_updated',
  'project_created',
  'project_updated',
  'project_deleted',
  'project_media_created',
  'room_created',
  'project_category_created',
  'client_created',
  'client_updated',
  'client_deleted',
  'invoice_created',
  'invoice_updated',
  'invoice_deleted',
  'employee_invited',
  'alert',
  'alert_read',
  'user_online',
  'user_offline',
  'presence_snapshot',
  'workspace_event',
  'social_account_connected',
  'social_account_disconnected',
  'social_sync_completed',
  'social_metrics_updated',
  'social_insight_created',
  'social_webhook_processed',
  // EMS events
  'ems:incident:created',
  'ems:incident:updated',
  'ems:incident:status_changed',
  'ems:unit:position',
  'ems:unit:status',
  'ems:unit:assigned',
  'ems:hospital:status',
  'ems:hospital:alert',
  'ems:dispatch:decision',
  'ems:ai:insight',
  'ems:predictive:alert',
  'ems:system:alert',
  'ems:workflow:triggered',
] as const

export type RealtimeEventName = (typeof REALTIME_EVENTS)[number]

export type RealtimeWorkspaceEvent = {
  type: RealtimeEventName
  payload: unknown
  at: string
}

const LEGACY_TO_CANONICAL_EVENT = {
  task_created: 'task.created',
  task_updated: 'task.updated',
  task_deleted: 'task.deleted',
  task_submission_created: 'task.submission.created',
  comment_created: 'comment.created',
  comment_updated: 'comment.updated',
  project_created: 'project.created',
  project_updated: 'project.updated',
  project_deleted: 'project.deleted',
  project_media_created: 'project.media.created',
  room_created: 'room.created',
  project_category_created: 'project.category.created',
  client_created: 'client.created',
  client_updated: 'client.updated',
  client_deleted: 'client.deleted',
  invoice_created: 'invoice.created',
  invoice_updated: 'invoice.updated',
  invoice_deleted: 'invoice.deleted',
  employee_invited: 'employee.invited',
  alert: 'notification.created',
  alert_read: 'notification.read',
  user_online: 'presence.user.online',
  user_offline: 'presence.user.offline',
  presence_snapshot: 'presence.snapshot',
  workspace_event: 'workspace.event',
  social_account_connected: 'social.account.connected',
  social_account_disconnected: 'social.account.disconnected',
  social_sync_completed: 'social.sync.completed',
  social_metrics_updated: 'social.metrics.updated',
  social_insight_created: 'social.insight.created',
  social_webhook_processed: 'social.webhook.processed',
} satisfies Partial<Record<RealtimeEventName, RealtimeEventName>>

const CANONICAL_TO_LEGACY_EVENT = Object.fromEntries(
  Object.entries(LEGACY_TO_CANONICAL_EVENT).map(([legacy, canonical]) => [canonical, legacy])
) as Partial<Record<RealtimeEventName, RealtimeEventName>>

export function canonicalRealtimeEventName(type: RealtimeEventName): RealtimeEventName {
  return (LEGACY_TO_CANONICAL_EVENT as Partial<Record<RealtimeEventName, RealtimeEventName>>)[type] ?? type
}

export function legacyRealtimeEventName(type: RealtimeEventName): RealtimeEventName | null {
  return CANONICAL_TO_LEGACY_EVENT[type] ?? (type.includes('.') ? null : type)
}
